### ISSUE TITLE
Changing Jambonz API Server Base URL not possible

### ISSUE THREAD

**Issue by Catharsis68** [jambonz/chrome-extension-dialer#31]
How to reproduce:

1. Go to "Settings Advanced"
2. Set a URL like `https://api.foo.bar/api/v1`
3. Set a valid Account SID + API Key
4. Save
5. Change the API Server Base URL to `https://api.foo.bar/v2`
6. Save

Expected: 
URL is being changed to `https://api.foo.bar/v2`

Actual:
The URL remains `https://api.foo.bar/api/v1`

[Screencast](https://cognigy-my.sharepoint.com/:v:/p/m_frindt/Edkcvsrf_apGr212sFcINxIBUfyo03PBceyzQKTICpmF2w?e=g5hVlz&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJTdHJlYW1XZWJBcHAiLCJyZWZlcnJhbFZpZXciOiJTaGFyZURpYWxvZy1MaW5rIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXcifX0%3D)

**Comment by xquanluu** [comment]
This issue is because Dialer will autocomplete the base URL based on current Jambonz API server. Currently Jambonz just support /v1

If we want to support any string can be base URL then we have 2 options:
1/ @davehorton agree on this and I will open new PR for that
2/ YOu can do your own build by changing this: https://github.com/jambonz/chrome-extension-dialer/blob/main/src/window/settings/advanced.tsx#L57C18-L57C30

**Comment by davehorton** [comment]
@Catharsis68 what is this "v2" api you want to reach?
